# Generated by Django 6.1 on 2026-09-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('horario', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
