# Generated by Django 6.1.1 on 2026-09-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='qr_code',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saida',
            name='responsavel',
            field=models.CharField(default='0000', max_length=100),
            preserve_default=False,
        ),
    ]
